### ISSUE TITLE
Differences between frontend and server

### ISSUE THREAD

**Issue by longnguyen11288** [HospitalRun/frontend#104]
How does frontend and server connect? I noticed both are connecting to couchdb directly

**Comment by jkleinsc** [comment]
@longnguyen11288 See https://github.com/HospitalRun/server/blob/master/README.md

Basically HospitalRun/server is a Node.js server that is intended to be used in production deployments of HospitalRun.  The compiled frontend directory goes into a directory called public when deploying the server.
