### ISSUE TITLE
Ember is going to 2.0

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/frontend#107]
[Ember is going to 2.0 soon](http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html). Just wanted to make sure it's on our radar, and find out if we have any plans to upgrade, and start a place to track upgrade progress/things to do.

**Comment by broerse** [comment]
Don't know if you can switch but Ember-Pouch will also be an Ember-CLI addon on June 12.

**Comment by jkleinsc** [comment]
@jglovier yes, this is what I mentioned the other day.  I am currently working on migrating to Ember 1.12 which will set us up for moving to Ember 2,0 and @broerse part of that migration is to move to ember-pouch

**Comment by broerse** [comment]
@jkleinsc Ember Pouch is now 2.0.0 and a CLI addon,

**Comment by jglovier** [comment]
Cool - closing out since it's on your radar and sounds like you have a migration strategy.
