### ISSUE TITLE
Add a category field to Inventory

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/frontend#111]
Can we add a ‘category’ field (with a drop down list)? This will be a very helpful field for searching, organizing, and reporting. Some of the categories that we regularly use are ( I can run this by the other EDs, if interested/necessary):

 

Personal Protective Equipment (Gowns, gloves, masks, caps, coverings, etc.)
Injection, Infusion, and Intravenous (Needles, catheters, etc.)
Pharmaceutical / Medication
Wound Care (Gauze, bandages,
Surgical (Blades, sutures,
Anesthesia
Laboratory
Physical Therapy (Plaster, boots, slings, etc.)
Durable Medical (Crutches, walkers, braces, etc.)
Instruments

**Comment by jkleinsc** [comment]
This category is redundant with the existing type field.  The type field can be used for this purpose.  The only caveat is that medication should be entered in as the type medication so that the pharmacy/medication pieces of HospitalRun can correctly identify inventory items that are medication.
