### ISSUE TITLE
Adding a size to inventory

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/frontend#112]
Can we add a ‘size’ field? This is very important to enter discrete items (e.g. gloves: size 7, 8, 9; knee brace: size S, M, L, XL, XXL; bandage: 3in, 4 in, 5 in; amoxicillin: 125ml, 250mg, 500mg, etc.; containers: 1 gal, 5 gal, etc.). You see where I’m heading…

**Comment by jkleinsc** [comment]
@tangollama I believe when we discussed this with Brian, we came to the conclusion that this could be accomplished by using naming standards in inventory item names.

**Comment by tangollama** [comment]
Agreed.
