### ISSUE TITLE
Consider a "local name" or common name for Inventory

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/frontend#113]
Is it possible to add a ‘National Name’ field? This is where we would enter the local language nomenclature.

**Comment by jkleinsc** [comment]
I believe the cross reference field would be an ideal place to put this information.  Its searchable and if you think about it national name is a kind of cross reference.

**Comment by jkleinsc** [comment]
Closing this because cross reference can be used for this purpose if needed
