### ISSUE TITLE
Layout of navigation needs some fixes

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/frontend#122]
There is an unneeded scrollbar on the navigation pane and the search icon is not in the right place.  See attached screenshot:
![screen shot 2015-07-08 at 12 26 08 pm](https://cloud.githubusercontent.com/assets/609052/8575963/d34604be-256c-11e5-963c-b7d728752cb2.png)

**Comment by jglovier** [comment]
What OS/Browser/Ver are you on?

**Comment by jglovier** [comment]
This is how it looks for me.

![image](https://cloud.githubusercontent.com/assets/1319791/8576055/785aba58-256d-11e5-9ecb-cc79d27e412f.png)

**Comment by jkleinsc** [comment]
OSX Yosemite Chrome 43

**Comment by jkleinsc** [comment]
I still don't understand why you would use overflow: scroll

**Comment by jkleinsc** [comment]
FYI... this is using the master branch

**Comment by jglovier** [comment]
I can't reproduce this. Can we setup a time to screenshare with Screenhero and I can try to diagnose on your machine?

**Comment by jglovier** [comment]
One thing that's bizarre that stands out to me in your screenshot is the scrollbar types. Even when scrollbars are present for me in Chrome, they don't affect the layout, and they don't have a white background, they have a transparent background.

![image](https://cloud.githubusercontent.com/assets/1319791/8599068/5242d14c-262c-11e5-8cde-89644e0aa42b.png)

**Comment by jglovier** [comment]
You're not in a VM or something, right?

**Comment by jkleinsc** [comment]
@jglovier I just verified this.  When I plugin an external monitor, I get the white scrollbars.  When I unplug, I get the black scrollbars.  Its some weird mac thing.  Here is someone else on SO getting the same issue:
http://stackoverflow.com/questions/21157231/mac-os-x-scrollbar-is-sometimes-white-transparent-and-sometimes-black-transpare

**Comment by jglovier** [comment]
:cool: That's so strange, because I'm on an external monitor and I can't reproduce this. Anyway, glad you found the fix. Thx.

**Comment by jglovier** [comment]
Also, the SO issue you linked to had to do with the scrollbar color itself, but not the appearance of a scrollbar background that affects the box layout. So that doesn't really explain it.

**Comment by jkleinsc** [comment]
@jglovier it was my external mouse.  When I plugged it in it caused the scrollbars to show.  I changed the setting here for Show scroll bars from Automatically based on mouse or trackpad to When scrolling and not it always shows the black bar and only when scrolling:
![screen shot 2015-07-09 at 11 58 23 am](https://cloud.githubusercontent.com/assets/609052/8600105/1affc3d8-2632-11e5-9cf1-cfeb890ff4db.png)

**Comment by jkleinsc** [comment]
@jglovier BTW -- I think if we left the overflow: scroll in the issue would reproduce in Windows because windows doesn't automatically hide scrollbars, but this feature in OSX does.

**Comment by jglovier** [comment]
Whoaaaaa interesting. Good find. :mag: :eyes: :+1: 

Reopening because I should address the breakage of the search bar regardless. That's a bit too fragile for my comfort, and who knows what else might trigger those scrollbars (e.g. a scenario where the scrollbar does need to appear for content, and the user has a mouse...like in the Philippines I'm guessing lol).

**Comment by jkleinsc** [comment]
I think I you factor in for a slightly wider scroll bar it would solve the search icon wrapping to the next line.

**Comment by jglovier** [comment]
Yup. :+1:
