### ISSUE TITLE
Roadmap to Ember 2.x

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/frontend#142]
We need to update this project to to eventually get it to Ember 2.x.  There are several things that need to happen in order to do so:
1. Update to Ember 1.13.  One of the blockers to doing so is that the ember pouch adapter we are currently using isn't compatible with newer versions of ember/ember data.  The plan here is to change the adapter to [ember-pouch] (https://github.com/nolanlawson/ember-pouch).
2. Fix deprecation warnings
3. Update to Ember 2.x

**Comment by jglovier** [comment]
@jkleinsc may I suggest opening issues for each of those items, and then create a Milestone for `Ember 2.X` which you can associate with each of the issues?

**Comment by broerse** [comment]
ember-pouch 2.0.2 works super with ember-cli 1.13.1 I can recommend it.

**Comment by jkleinsc** [comment]
@jglovier Done

**Comment by jglovier** [comment]
@jkleinsc :metal: 

Could probably close this out now, as the Milestone will serve the same purpose.

**Comment by jkleinsc** [comment]
@jglovier Good point.  Closing.
