### ISSUE TITLE
Units for edit of first purchase of a new tem default back to ampule

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/frontend#19]
1. create a new item.   Enter minimal data:  change all units to "each", enter a quantity. Save.
2. on the new item, edit that first purchase.   Notice on dialog Units default back to ampule

Also, after a location adjustment (Remove), the edit purchase dialog no longer displays the unit.  

See 9 inch washclothes vs 7 inch washclothes in beta site.  9in show this issue, 7 in no longer shows units in edit purchase dialog

**Comment by jkleinsc** [comment]
Closing this bug because we removed the edit purchase screen (purchases can be adjusted via inventory adjustments).
