### ISSUE TITLE
Disabled save button is bad UX

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/frontend#98]
Right now when a form isn't valid and/or all of the required fields aren't filled in, the save button is disabled until the form is valid.  This has lead to users reporting that they can't save.  At the very least we should display a message when a user tries to click a disabled button.  Ideally that message would tell the user which field(s) are currently invalid.

**Comment by jglovier** [comment]
![carl-sagan-youre-awesome](https://cloud.githubusercontent.com/assets/1319791/7193937/3230036e-e475-11e4-9b2a-403473bb77f2.gif)
